# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background: #3e3461\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image_list = QtWidgets.QListWidget(self.centralwidget)
        self.image_list.setGeometry(QtCore.QRect(5, 71, 111, 471))
        self.image_list.setStyleSheet("border-radius:10px;\n"
"border: 3px solid white;")
        self.image_list.setObjectName("image_list")
        self.open_btn = QtWidgets.QPushButton(self.centralwidget)
        self.open_btn.setGeometry(QtCore.QRect(10, 10, 101, 41))
        self.open_btn.setStyleSheet("color: white;\n"
"border: 3px solid white;\n"
"border-radius: 10px;\n"
"background:#07f57e;")
        self.open_btn.setObjectName("open_btn")
        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_btn.setGeometry(QtCore.QRect(710, 10, 75, 41))
        self.save_btn.setStyleSheet("color: white;\n"
"border: 3px solid white;\n"
"border-radius:10px;\n"
"background:#f5073b;")
        self.save_btn.setObjectName("save_btn")
        self.right_btn = QtWidgets.QPushButton(self.centralwidget)
        self.right_btn.setGeometry(QtCore.QRect(130, 10, 111, 41))
        self.right_btn.setStyleSheet("color: white;\n"
"border: 3px solid white;\n"
"border-radius: 10px;\n"
"background:#d68a27;")
        self.right_btn.setObjectName("right_btn")
        self.left_btn = QtWidgets.QPushButton(self.centralwidget)
        self.left_btn.setGeometry(QtCore.QRect(260, 10, 101, 41))
        self.left_btn.setStyleSheet("color: white;\n"
"border: 3px solid white;\n"
"border-radius: 10px;\n"
"background:#d68a27;")
        self.left_btn.setObjectName("left_btn")
        self.blure_btn = QtWidgets.QPushButton(self.centralwidget)
        self.blure_btn.setGeometry(QtCore.QRect(380, 10, 101, 41))
        self.blure_btn.setStyleSheet("color: white;\n"
"border: 3px solid white;\n"
"border-radius:10px;\n"
"background:#d68a27;\n"
"")
        self.blure_btn.setObjectName("blure_btn")
        self.blackwhite_btn = QtWidgets.QPushButton(self.centralwidget)
        self.blackwhite_btn.setGeometry(QtCore.QRect(500, 10, 101, 41))
        self.blackwhite_btn.setStyleSheet("color: white;\n"
"border: 3px solid white;\n"
"border-radius:10px;\n"
"background:#d68a27;\n"
"")
        self.blackwhite_btn.setObjectName("blackwhite_btn")
        self.mirror_btn = QtWidgets.QPushButton(self.centralwidget)
        self.mirror_btn.setGeometry(QtCore.QRect(620, 10, 81, 41))
        self.mirror_btn.setStyleSheet("color: white;\n"
"border: 3px solid white;\n"
"border-radius:10px;\n"
"background:#d68a27;")
        self.mirror_btn.setObjectName("mirror_btn")
        self.image_label = QtWidgets.QLabel(self.centralwidget)
        self.image_label.setGeometry(QtCore.QRect(130, 70, 651, 471))
        self.image_label.setStyleSheet("color: white;\n"
"border: 3px solid white;\n"
"border-radius:10px;\n"
"")
        self.image_label.setObjectName("image_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Easy Editor"))
        self.open_btn.setText(_translate("MainWindow", "Відкрити папку"))
        self.save_btn.setText(_translate("MainWindow", "Зберегти"))
        self.right_btn.setText(_translate("MainWindow", "Повернути вправо"))
        self.left_btn.setText(_translate("MainWindow", "Повернути вліво"))
        self.blure_btn.setText(_translate("MainWindow", "Розмиття"))
        self.blackwhite_btn.setText(_translate("MainWindow", "Чорно білий"))
        self.mirror_btn.setText(_translate("MainWindow", "Відзеркалити"))
        self.image_label.setText(_translate("MainWindow", "Зображення"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
